### ISSUE TITLE
Linux version

### ISSUE THREAD

**Issue by brpaz** [vutran/dext#119]
First of all, this project looks really good.
I was looking for a tool like this for some time. 
Dont know if you know [hain](https://github.com/appetizermonster/hain)? its a similar project to dext but seems to have few activity in last months so I think I will opt with dext.

I have cloned the repo and have its working fine in Linux with Linux mint 18 with cinnamon.

Just have an issue, not sure its related to Linux or not. I have 2 monitors and dext allays opens on the primary monitor. I know that its possible to detect the active monitor in Electron. I might take a look if I have time.

Also when using for example the github plugin, I have some black borders around the suggestions box.

**Comment by z3t0** [comment]
> Also when using for example the github plugin, I have some black borders around the results box.

maybe create a second issue for this with a screenshot so other linux users are aware, also if there's a linux label that might be useful

**Comment by vutran** [comment]
> First of all, this project looks really good.
I was looking for a tool like this for some time.
Dont know if you know hain? its a similar project to dext but seems to have few activity in last months so I think I will opt with dext.

Thanks for the awesome words. I noticed Hain is also an Electron powered launcher as well. I believe the goals are for Windows users. Our plans for Dext is to be cross platform and also be compatible with Alfred node plugins by following Alfred's filter schema (see [alfy](https://github.com/sindresorhus/alfy)) and hopefully can be compatible with packal packages. 

> Just have an issue, not sure its related to Linux or not. I have 2 monitors and dext allays opens on the primary monitor. I know that its possible to detect the active monitor in Electron. I might take a look if I have time.

Feel free to send a PR for this.

> Also when using for example the github plugin, I have some black borders around the results box.

May be an issue with the default theme. I can take a look at this this week unless you get to it before I do.

**Comment by pacharanero** [comment]
I'm keen to help out with the Linux version. I'm testing on Linux Mint 18 Cinnamon.

I've forked the repo, cloned locally, done an `npm install` and launched from the `master` branch using `npm start`. Is this correct?

When I do that I get an error:

```
Uncaught Exception:
TypeError: Error processing argument at index 1, conversion failure from 54.5
    at TypeError (native)
    at repositionWindow (/home/marcus/code/dext/app/main/index.js:105:7)
    at App.createWindow (/home/marcus/code/dext/app/main/index.js:304:3)
    at emitTwo (events.js:111:20)
    at App.emit (events.js:191:7)
```

**Comment by vutran** [comment]
@pacharanero I never knew Linux used floats for window positions. `Math.floor` would be easier to attract new contributors to follow since not many people know bitwise ops. The trade off is perf since `~~` is more performance than `Math.floor`.

**Comment by pacharanero** [comment]
@vutran I think it's the division by 2 in the preceding few lines of code that is resulting in the float. I'll fix it with Math.floor and submit a PR

**Comment by pacharanero** [comment]
Dext now works for me in Linux Mint 18, however it doesn't search or launch applications yet. (Kind of essential functionality in a Launcher!). I'd like to help implement this - which I presume is going to require OS-specific code - but I have no idea where to even start... Anyone else out there wanna join in on the Linux version?

**Comment by vutran** [comment]
> Dext now works for me in Linux Mint 18, however it doesn't search or launch applications yet. (Kind of essential functionality in a Launcher!). I'd like to help implement this - which I presume is going to require OS-specific code - but I have no idea where to even start... Anyone else out there wanna join in on the Linux version?

Ideally, we would want to create this as a core plugin. Take a look at the [plugin docs](https://github.com/vutran/dext/blob/develop/docs/PLUGINS.md) as a start on how to create a plugin. You can also reference the current [core plugins](https://github.com/vutran/dext/tree/develop/resources/plugins) for some working examples.

**Comment by kmf** [comment]
I would love a Linux version, is there any testing to be done?

**Comment by brpaz** [comment]
@kmf I am running Dext on Linux Mint 18 and haven't found any issues.

**Comment by pacharanero** [comment]
@kmf I think the bug I experienced on LM18 was due to my HiDPI screen, the window placement was for some reason returning an unexpected value. We've fixed this now.

@kmf but I would still regard the current lack of app search and launch as a fairly big issue! This is not yet implemented in Linux - see issue #130  (I have no clue how one goes about doing this either but would happily have a go if someone more knowledgeable gives me a push in the right direction...)

**Comment by vutran** [comment]
@pacharanero We have an open PR that is a WIP that you can check out [here](https://github.com/vutran/dext/pull/140).
