### ISSUE TITLE
yarn run build:prod error

### ISSUE THREAD

**Issue by soredake** [vutran/dext#171]
```
~/git/dext develop
❯ yarn run build:prod
yarn run v0.19.0
$ cross-env NODE_ENV=production webpack --config webpack.config.prod.js 
Hash: c299843db90bd37ddc7b
Version: webpack 2.2.1
Time: 3759ms
    Asset     Size  Chunks             Chunk Names
bundle.js  86.9 kB       0  [emitted]  index
 [113] ./app/renderer/src/index.js 1.7 kB {0} [built] [failed] [1 error]
 [114] ./~/babel-polyfill/lib/index.js 833 bytes {0} [built]
 [115] ./~/core-js/fn/regexp/escape.js 107 bytes {0} [built]
 [284] ./~/core-js/modules/es7.string.match-all.js 1.04 kB {0} [built]
 [285] ./~/core-js/modules/es7.string.pad-end.js 337 bytes {0} [built]
 [286] ./~/core-js/modules/es7.string.pad-start.js 340 bytes {0} [built]
 [287] ./~/core-js/modules/es7.string.trim-left.js 215 bytes {0} [built]
 [288] ./~/core-js/modules/es7.string.trim-right.js 215 bytes {0} [built]
 [289] ./~/core-js/modules/es7.symbol.async-iterator.js 42 bytes {0} [built]
 [290] ./~/core-js/modules/es7.symbol.observable.js 39 bytes {0} [built]
 [291] ./~/core-js/modules/es7.system.global.js 143 bytes {0} [built]
 [292] ./~/core-js/modules/web.dom.iterable.js 881 bytes {0} [built]
 [295] ./~/core-js/shim.js 7.38 kB {0} [built]
 [296] ./~/regenerator-runtime/runtime.js 22.5 kB {0} [built]
 [297] multi babel-polyfill ./app/renderer/src/index 40 bytes {0} [built]
    + 283 hidden modules

WARNING in DedupePlugin: This plugin was removed from webpack. remove it from configuration.

ERROR in ./app/renderer/src/index.js
Module build failed: Error: Cannot find module '../../modules/es6.object.to-string'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/bausch/git/dext/node_modules/core-js/library/fn/symbol/index.js:2:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/bausch/git/dext/node_modules/babel-runtime/core-js/symbol.js:1:93)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/bausch/git/dext/node_modules/babel-runtime/helpers/typeof.js:9:15)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/bausch/git/dext/node_modules/babel-core/lib/transformation/file/index.js:6:16)
    at Module._compile (module.js:570:32)
 @ multi babel-polyfill ./app/renderer/src/index
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

**Comment by vutran** [comment]
@soredake What version node are you running? Try removing the `node_modules` and re-running `npm install` or `yarn install` with the latest Node version.
